POST http://localhost:4000/employee-emails
Content-Type: application/json
 
{
    "email":"ks00700145@unistechnosoft.com",
    "passWord":"Sravanthi@1236"
}

###
POST http://localhost:4000/employee-emails-data
Content-Type: application/json

###
GET http://localhost:4000/employeeDataAdd

###
POST http://localhost:4000/employeeDataAdd
Content-Type: application/json

###
POST http://localhost:4000/employeesLoginPost
Content-Type: application/json
Accept: application/json
 
{
    "gmail":"Cp00700062@unistechnosoft.com",
    "employeePassWord":"D2e&fgh456"
}


###
POST http://localhost:4000/taskAssignPost
Content-Type: application/json
 
{
    "taskNumber1":"gdfdsfsdfsdfdsf",
    "employeeId1":"gangadhar",
    "taskDiscription1":"taskDiscription1",
    "pdfFile1":"pdfFile1",
    "taskCreateTime1":"taskCreateTime1",
    "taskAssignedTime1":"taskAssignedTime1",
    "assignedStatus1":"assignedStatus1",
    "completeDateTime1":"completeDateTime1",
    "completeStatus1":"completeStatus1",
    "employeeComment1":"employeeComment1",
    "managerComment1":"managerComment1"
}

###
POST  http://localhost:4000/tasksData
Content-Type: application/json

{
    "empId":"lg00700049"
}

###
GET http://localhost:4000/getAllTasks

###
PUT http://localhost:4000/updateTaskAssigned
Content-Type: application/json

{
    "taskNum":"bf1b86ae-7e6f-4bf0-a8f5-a78d6ad30016",
    "taskAssignedTime3":"3 pm",
    "assignedStatus3":"successfully assinged"

}

###
PUT http://localhost:4000/updateTaskAssigned2
Content-Type: application/json

{
    "taskNum":"96ba31c4-dc4a-4da0-99d5-40311883ca40",
    "taskDiscription1":"Create Inventory Table Document",
    "pdfFile1":"pdfFile 888888",
     "managerComment1":"Create and attach the doc to outlook"
}

###
DELETE http://localhost:4000/oneTaskDelete
Content-Type: application/json

{
    "taskNum":"d0806cb4-bd41-424e-9895-644ff43d5d0d"
}

###
POST http://localhost:4000/EmployeeDetails
Content-Type: application/json

{
    "email":"nr00700036@unistechnosoft.com"
}

###
PUT http://localhost:4000/EmployeeDetailsUpdate
Content-Type: application/json

{
    "email":"NS00700109@unistechnosoft.com",
    "mobileNumber1": "7702441016",
    "skillSet2": "React Native"
}

###
POST http://localhost:4000/getEmployeeAllTasks
Content-Type: application/json

{
    "emplId":"lg00700049"
}

###
PUT http://localhost:4000/updateCreateStatus
Content-Type: application/json

{
    "taskId2":"e174d9ff-28f1-45d4-baf5-3a65b117bded",
    "completedTime2":"2 pm",
    "status2":"Completed",
    "empComment2":"Getting some error but we resolved it"
}

###
POST http://localhost:4000/superAdminCredential
Content-Type: application/json

{
    "name":"Ganga",
    "passWord2":"ganga7702"
}

###
POST http://localhost:4000/superAdminLogin
Content-Type: application/json

{
    "name":"Ganga",
    "passWord2":"ganga7702"
}